# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bmcp < Formula
  desc "BORIS MCP to CLI converter"
  homepage "https://github.com/sirob-tech/boris-mcp-cli"
  version "0.11.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.11.2/bmcp-darwin-amd64.tar.gz"
      sha256 "7711757785cb8fc9dc0b43065f87ecf61c12cb2b41c285fb59a11b24f5c01dc8"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.11.2/bmcp-darwin-arm64.tar.gz"
      sha256 "7c933704749320474578afddf242549c9c391819f06d3ddefbed04c6e8d5e879"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.11.2/bmcp-linux-amd64.tar.gz"
      sha256 "42cde2c8f2d4f345904503823c89453ee8ca7d08eb6f69571884a6f031ceffab"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.11.2/bmcp-linux-arm64.tar.gz"
      sha256 "7f5b7620113d4bbce76ca8b88672982cc8e8cf6b1a3e3b98f5e738c99921156d"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  test do
    system "#{bin}/bmcp", "version"
  end
end
