# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bmcp < Formula
  desc "BORIS MCP to CLI converter"
  homepage "https://github.com/sirob-tech/boris-mcp-cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.5.0/bmcp-darwin-amd64.tar.gz"
      sha256 "314ffb26292fcd5debba44d6f22557b378b157f4b76ea2e04c1da771865174fa"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.5.0/bmcp-darwin-arm64.tar.gz"
      sha256 "f4373b0714317d03dbf5e087882654b18acf27b0cd63ecbaa5942afb411012f6"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.5.0/bmcp-linux-amd64.tar.gz"
      sha256 "ff1a78a349ca4c35177c23403900635ba660d2ab3e87c22e02f6a270dec5b69e"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.5.0/bmcp-linux-arm64.tar.gz"
      sha256 "8bd0540cded59641443069aba15cafa8f4d1f5793c3ca6faae4462bf544fa163"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  test do
    system "#{bin}/bmcp", "version"
  end
end
