# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bmcp < Formula
  desc "BORIS MCP to CLI converter"
  homepage "https://github.com/sirob-tech/boris-mcp-cli"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.10.0/bmcp-darwin-amd64.tar.gz"
      sha256 "c18546613feca48ad724979272d929966560ee40fa564f27c97a1d5b395105b9"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.10.0/bmcp-darwin-arm64.tar.gz"
      sha256 "1eabb5a1692b73787d198f49aa65e2f8c1558e50dabd3aa1ad45a39dcb36c5ef"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.10.0/bmcp-linux-amd64.tar.gz"
      sha256 "737ad189a975bb9f2aa24d92db0b77ab3cc9294a42b62f6f8e40d51277dd7b03"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.10.0/bmcp-linux-arm64.tar.gz"
      sha256 "207056421236dd410bb16d38cbab05eb240049ad7e9859eba418ad50b6833266"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  test do
    system "#{bin}/bmcp", "version"
  end
end
